-- Run this in a Snowflake Worksheet to set up the necessary objects

-- 1. Create a Warehouse (Compute resource)
CREATE OR REPLACE WAREHOUSE TENNIS_WH
    WITH WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

-- 2. Create the Database
CREATE OR REPLACE DATABASE TENNIS_DB;

-- 3. Create the Schema
CREATE OR REPLACE SCHEMA TENNIS_DB.RAW_DATA;

-- 4. Switch to use these objects
USE WAREHOUSE TENNIS_WH;
USE DATABASE TENNIS_DB;
USE SCHEMA RAW_DATA;

-- 5. Create the tables (matches Python code)
CREATE OR REPLACE TABLE MATCHES (
    MATCH_ID VARCHAR(50) PRIMARY KEY,
    PLAYER1_NAME VARCHAR(50),
    PLAYER2_NAME VARCHAR(50),
    VIDEO_FILE VARCHAR(255),
    MATCH_DATE TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP()
);

CREATE OR REPLACE TABLE TRACKING_EVENTS (
    EVENT_ID VARCHAR(50) PRIMARY KEY,
    MATCH_ID VARCHAR(50),
    RALLY_ID VARCHAR(50),
    TIMESTAMP TIMESTAMP_NTZ,
    RAW_DATA VARIANT,
    CONSTRAINT fk_tracking_match FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(MATCH_ID)
);

CREATE OR REPLACE TABLE MATCH_STATS (
    STATS_ID VARCHAR(50) PRIMARY KEY DEFAULT UUID_STRING(),
    MATCH_ID VARCHAR(50),
    SUMMARY_JSON VARIANT,
    RALLIES_JSON VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT fk_stats_match FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(MATCH_ID)
);

CREATE OR REPLACE TABLE COACHING_INSIGHTS (
    INSIGHT_ID VARCHAR(50) PRIMARY KEY DEFAULT UUID_STRING(),
    MATCH_ID VARCHAR(50),
    PROMPT_TEXT STRING,
    LLM_RESPONSE_TEXT STRING,
    PROCESSED_RESPONSE_JSON VARIANT,
    CREATED_AT TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT fk_insight_match FOREIGN KEY (MATCH_ID) REFERENCES MATCHES(MATCH_ID)
);
