import { useEffect, useState } from "react";

const WHITE = "rgba(255,255,255,0.95)";

export function LatestAnalysis({ videoUrl, matchId }: { videoUrl: string; matchId: string }) {
    const [data, setData] = useState<any>(null);

    useEffect(() => {
        if (!matchId) return;
        // Fetch the JSON analysis file generated by the python backend
        fetch(`http://localhost:5001/output-videos/analysis_${matchId}.json`)
            .then(res => res.json())
            .then(setData)
            .catch(err => console.error("Failed to load analysis JSON", err));
    }, [matchId]);

    if (!data) return null;

    // Parse data from the backend JSON structure
    const metrics = data.behavioral_metrics?.player || {};
    const matchMetrics = data.behavioral_metrics?.match || {};
    const insight = data.coaching_insight || "";

    // Parse sections from the raw coaching text using regex
    const problem = insight.match(/THE PROBLEM\s*\n(.*?)(?=\n[A-Z]|$)/s)?.[1]?.trim();
    const fix = insight.match(/YOUR FIX\s*\n(.*?)(?=\n[A-Z]|$)/s)?.[1]?.trim();
    const mentalBlock = insight.match(/MENTAL BLOCK\s*\n(.*?)(?=\n[A-Z]|$)/s)?.[1]?.trim();
    const mantra = insight.match(/SAY THIS BEFORE SERVING\s*\n"(.*?)"/s)?.[1]?.trim();
    const coachMessage = insight.match(/COACH: (.*?)(?=\n|=)/s)?.[1]?.trim();

    return (
        <div style={{
            width: "100%",
            maxWidth: 1000,
            margin: "0 auto 40px",
            background: "rgba(25,25,25,0.6)",
            border: "1px solid rgba(255,255,255,0.1)",
            borderRadius: 24,
            padding: 30,
            backdropFilter: "blur(20px)",
        }}>
            {/* Header / Title */}
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: 30 }}>
                <div>
                    <div style={{ fontSize: 13, color: "rgba(255,255,255,0.5)", fontWeight: 700, letterSpacing: "0.05em", marginBottom: 6 }}>
                        LATEST ANALYSIS
                    </div>
                    <div style={{ fontSize: 32, fontWeight: 800, color: WHITE }}>
                        Recording {matchId}
                    </div>
                </div>
                {/* AI Badge */}
                <div style={{
                    background: "rgba(59, 130, 246, 0.2)",
                    border: "1px solid rgba(59, 130, 246, 0.4)",
                    padding: "6px 12px",
                    borderRadius: 20,
                    fontSize: 12,
                    fontWeight: 700,
                    color: "#60a5fa",
                    display: "flex",
                    alignItems: "center",
                    gap: 6
                }}>
                    ✨ AI COACH ACTIVE
                </div>
            </div>

            {/* Grid Layout */}
            <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 30 }}>

                {/* Left Column: Stats & Video Thumb */}
                <div>
                    {/* Video Player (Mini) */}
                    <div style={{
                        borderRadius: 16,
                        overflow: "hidden",
                        border: "1px solid rgba(255,255,255,0.1)",
                        marginBottom: 24,
                        aspectRatio: "16/9",
                        background: "#000"
                    }}>
                        <video
                            src={videoUrl}
                            controls
                            style={{ width: "100%", height: "100%", objectFit: "cover" }}
                        />
                    </div>

                    {/* Key Stats Grid */}
                    <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 }}>
                        <StatBox label="Total Shots" value={matchMetrics.total_shots || 0} />
                        <StatBox label="Rallies" value={matchMetrics.total_rallies || 0} />
                        <StatBox label="Avg Rally" value={`${matchMetrics.avg_rally_duration || 0}s`} />
                        <StatBox label="Forehand %" value={`${matchMetrics.forehand_pct || 0}%`} />
                        <StatBox label="Backhand %" value={`${matchMetrics.backhand_pct || 0}%`} />
                        <StatBox label="Aggression" value={metrics.aggression_index?.value || "N/A"} />
                    </div>
                </div>

                {/* Right Column: AI Coaching */}
                <div style={{ background: "rgba(0,0,0,0.3)", borderRadius: 20, padding: 24, border: "1px solid rgba(255,255,255,0.05)" }}>
                    <div style={{ fontSize: 18, fontWeight: 800, color: WHITE, marginBottom: 20, display: "flex", alignItems: "center", gap: 10 }}>
                        🤖 Your AI Coach
                    </div>

                    {coachMessage && (
                        <div style={{
                            fontSize: 20,
                            fontWeight: 600,
                            color: "#fff",
                            fontStyle: "italic",
                            marginBottom: 24,
                            paddingLeft: 16,
                            borderLeft: "4px solid #60a5fa"
                        }}>
                            "{coachMessage}"
                        </div>
                    )}

                    {problem && (
                        <InsightItem
                            label="THE PROBLEM"
                            text={problem}
                            color="rgba(239, 68, 68, 1)" // Red
                        />
                    )}

                    {fix && (
                        <InsightItem
                            label="YOUR FIX"
                            text={fix}
                            color="rgba(34, 197, 94, 1)" // Green
                        />
                    )}

                    {mentalBlock && (
                        <InsightItem
                            label="MENTAL BLOCK"
                            text={mentalBlock}
                            color="rgba(234, 179, 8, 1)" // Yellow
                        />
                    )}

                    {mantra && (
                        <div style={{ marginTop: 30, textAlign: "center", background: "rgba(255,255,255,0.05)", padding: 16, borderRadius: 12 }}>
                            <div style={{ fontSize: 11, color: "rgba(255,255,255,0.4)", textTransform: "uppercase", letterSpacing: "0.1em", marginBottom: 6 }}>
                                Say this before serving
                            </div>
                            <div style={{ fontSize: 18, fontWeight: 700, color: WHITE }}>
                                "{mantra}"
                            </div>
                        </div>
                    )}

                    {/* Fallback if no insight parsed */}
                    {!coachMessage && !problem && (
                        <div style={{ color: "rgba(255,255,255,0.5)", fontSize: 14 }}>
                            No detailed coaching insight available for this match yet.
                        </div>
                    )}
                </div>
            </div>
        </div>
    );
}

// Sub-components for cleaner code
function StatBox({ label, value }: { label: string, value: string | number }) {
    return (
        <div style={{
            background: "rgba(255,255,255,0.05)",
            borderRadius: 12,
            padding: "12px 16px",
            display: "flex",
            flexDirection: "column",
            gap: 4
        }}>
            <div style={{ fontSize: 12, color: "rgba(255,255,255,0.5)" }}>{label}</div>
            <div style={{ fontSize: 18, fontWeight: 700, color: WHITE }}>{value}</div>
        </div>
    );
}

function InsightItem({ label, text, color }: { label: string, text: string, color: string }) {
    return (
        <div style={{ marginBottom: 20 }}>
            <div style={{
                fontSize: 11,
                fontWeight: 800,
                color: color,
                marginBottom: 6,
                letterSpacing: "0.05em",
                textTransform: "uppercase"
            }}>
                {label}
            </div>
            <div style={{ fontSize: 15, color: "rgba(255,255,255,0.8)", lineHeight: 1.5 }}>
                {text}
            </div>
        </div>
    );
}
